project:
  type: website

website:
  title: "Morgane Hoffmann"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href : research.qmd
        text: Research
      - href : about.qmd
        text: Curriculum

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



